### PR TITLE
removed yuicompress options because it is no longer suported by less >= 1.5.0-b1

### PR DESCRIPTION
**Pull request by pwaleczek**
updated less npm dependency and removed yui compression test, because it was removed in 'less v1.5.0-b1'

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks for doing this!

**Comment by pwaleczek** [comment]
no problem, needed to fix this, for a work-related project

**Comment by pwaleczek** [comment]
also, could you update the npm package?

**Comment by jonschlinkert** [comment]
np

**Comment by pwaleczek** [comment]
great, thanks!

**Comment by jonschlinkert** [comment]
done

**Pull request merged**
